arrowParens: avoid
bracketSpacing: false
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

overrides:
  - files: "contracts/*.sol"
    options:
      tabWidth: 4
      explicitTypes: 'always'